### ISSUE TITLE
Small concern

### ISSUE THREAD

**Issue by cramik** [dundargoc/Schonhage-Strassen-algorithm#1]
Hi, was doing research on Strassen for a class assignment when I spotted this repo. If I understand correctly your thesis involved the use of this benchmarking code to compare it to FLINT, but there doesn't appear to be any actual results included or a link to thesis paper where I could see runtime results. I know it's the information will probably not benefit me, but it'd be nice to see the results without having to compile, install FLINT, etc.

**Comment by dundargoc** [comment]
Oh wow, I forgot this existed.

You're completely correct, I'm not sure why I didn't provide any benchmarks. If I'm being honest my masters thesis was a bit of an unfocused mess so I don't think I could provide anything of use. I will archive/private this repo so other unsuspecting people don't stumble on this. Thank you for the interest.
